### ISSUE TITLE
fzf-csh: could not find fzf executable. Is there any install stage / setup ?

### ISSUE THREAD

**Issue by hellovimo** [graahnul-grom/fzf-csh#4]
Hello @graahnul-grom 

1. I tried the steps provided in the setup.
2. But when I close all the terminals and re-open the .cshrc gets sourced, which sources the fzf-csh.csh and get the following below error

`fzf-csh: could not find fzf executable.
         make sure fzf is installed.
`
3. Was there any procedure to install these ? bcoz in the fzf-bash/zshrc we have the step called ~/.fzf/install, but in this flow there aren't any such step.

How to resolve this issue ?

**Comment by hellovimo** [comment]
Hello @graahnul-grom 

Think I figured out the issue.

1. Looks like first I need to install the actual fzf from "https://github.com/junegunn/fzf"
2. Then follow the steps provided in your page on how to setup your fzf-csh.
3. And then it worked. 


Awesome thanks a lot. Appreciate your contribution.   You can close the ticket.

**Comment by graahnul-grom** [comment]
Hi @hellovimo!
Glad to hear that you figured that out.
Thank you for your kind words, good luck!
